version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - "C:/qa_workspace_/ollama/ollama_data:/root/.ollama"
    restart: unless-stopped
    tty: true

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - "C:/qa_workspace_/ollama/qdrant_data:/qdrant/storage"
    restart: unless-stopped
